name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@544eadc6bf3d226fd7a7a9f0dc5b5bf7ca0675b9 # v1
      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile
      - name: Alex
        run: yarn alex
